# Notification vote
tokenNotification: TOKEN
urlNotification: monurl:8000
## Url get Vote
## Attention ! urlGetVote sera utilisée également pour /url?uuid='xxx'&nbMonth='[mmYYYY]
## Attention ! monUrlGetVote sera utilisée également pour /url?nbMonth='[mmYYYY]
urlGetVote: monUrlGetVote?uuid=:8000
# Connexion BDD
tokenReward: TOKEN
urlReward: monapi:8000
#Path use for transfert Json files to DB
pathFilesJson: /plugins/RandomReward/Players/
#Path use to give random reward
#default : "plugins\\randomreward\\rewards.yml"
pathFileReward: "plugins\\randomreward\\rewards.yml"
# Debug (enable/disable)
debug: enable
