main: fr.lataverne.randomreward.RandomReward

name: RandomReward

version: 1.21

api-version: 1.21

authors:
  - Black_Fox3000

commands:
  randomreward:
    aliases:
      - rr

permissions:
  rr.give:
    default: op